<a href="https://colab.research.google.com/github/DakshayiniRayini/Dakshayini_INFO5731_Fall2021/blob/main/Dakshayini_INFO5731_Fall2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## The second In-class-exercise (09/22/2022, 40 points in total)

The purpose of this exercise is to understand users' information needs, then collect data from different sources for analysis.

Question 1 (10 points): Describe an interesting research question (or practical question) you have in mind, what kind of data should be collected to answer the question(s)? How many data needed for the analysis? The detail steps for collecting and save the data.

In [ ]:
# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

'''
Please write you answer here:

. The research question I have to analyse is the places to be visited by the tourists based on the previous search history.
. For this, I have to collect the data of the search history of the tourists that are visible to users from website by using filters of places that have searched. 
. It is regarding search analysis.
. We can collect the data and then plot to analyse the search history as analysis.

'''

'\nPlease write you answer here:\n\n. The research question I have to analyse is the places to be visited by the tourists.\n. For this, I have to collect the data of the search history o the tourists that are visible to users from website by using filters. \n. It is regarding sentinent analysis.\n. We can collect the data and then plot to analyse the search history as analysis.\n\n'

Question 2 (10 points): Write python code to collect 1000 data samples you discussed above.

In [ ]:
# You code here (Please add comments in the code):
import pandas as pd

import requests
from bs4 import BeautifulSoup

def getAmazon(sea_qu):
    url1="https://www.amazon.com/s?k="+sea_qu
    print(url1)
    pg=requests.get(url1,headers=header)
    if pg.status_code==200:
        return pg
    else:
        return "Error"

s_query="iphone+10"
base_url="https://www.amazon.com/s?k="

url_1=base_url+s_query

header={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36','referer':'https://www.amazon.com/s?k=nike+shoes+men&crid=28WRS5SFLWWZ6&sprefix=nike%2Caps%2C357&ref=nb_sb_ss_organic-diversity_2_4'}

s_response=requests.get(url_1,headers=header)

cookies={} 
cookies_1 = s_response.cookies
prod_name=[]
resp=getAmazon('iphone+10')
so=BeautifulSoup(resp.content)
for i in so.findAll("span",{'class':'a-size-base-plus a-color-base a-text-normal'}): 
    prod_name.append(i.text) 
def Searchasing(asin1):
    url1="https://www.amazon.com/dp/"+asin1
    print(url1)
    pg=requests.get(url1,cookies=cookies_1,headers=header)
    if pg.status_code==200:
        return pg
    else:
        return "Error"
def Searchrev(rev_li):
    url_2="https://www.amazon.com"+rev_li
    print(url_2)
    pg=requests.get(url_2,cookies=cookies_1,headers=header)
    if pg.status_code==200:
        return pg
    else:
        return "Error"
data_asign=[]
resp=getAmazon('UnderArmour+shoes+men')
so=BeautifulSoup(resp.content)

for i in so.findAll("div",class_="sg-col-4-of-12 s-result-item s-asin sg-col-4-of-16 AdHolder sg-col sg-col-4-of-20"):

    data_asign.append(i['data-asign'])
li=[]
for i in range(len(data_asign)):
    resp=Searchasing(data_asign[i])
    so=BeautifulSoup(resp.content)
    for i in so.findAll("a",{'data-hook':"see-all-reviews-link-foot"}):
        li.append(i['href'])
rev=[]
rev_title = []
rev_date = []
rev_star = []
name1 = []
for j in range(len(li)):
    for k in range(50):
        resp=Searchrev(li[j]+'&pageNumber='+str(k))
        so=BeautifulSoup(resp.content)
        for i in so.findAll("span",{'data-hook':"review-body"}):
            rev.append(i.text)
        for i in so.findAll("span",{'data-hook':"review-title"}):
            rev_title.append(i.text)
        for i in so.findAll("span",{'data-hook':"review-date"}):
            rev_date.append(i.text)
        for i in so.findAll("span",{'data-hook':"review-star-rating"}):
            rev_star.append(i.text)
        for i in so.findAll('span',class_='a-profile-name'):
            name1.append(i.text)

https://www.amazon.com/s?k=iphone+10
https://www.amazon.com/s?k=UnderArmour+shoes+men

Question 3 (10 points): Write python code to collect 1000 articles from Google Scholar (https://scholar.google.com/), Microsoft Academic (https://academic.microsoft.com/home), or CiteSeerX (https://citeseerx.ist.psu.edu/index), or Semantic Scholar (https://www.semanticscholar.org/), or ACM Digital Libraries (https://dl.acm.org/) with the keyword "information retrieval". The articles should be published in the last 10 years (2012-2022).

The following information of the article needs to be collected:

(1) Title

(2) Venue/journal/conference being published

(3) Year

(4) Authors

(5) Abstract

In [ ]:
# You code here (Please add comments in the code):
    
from bs4 import BeautifulSoup
from urllib.request import Request, urlopen
from urllib.error import HTTPError
import json
import re 
import pandas as pd
final_count = 0
c = 0

result = {"Title":[], "Authors":[], "Year":[], "Abstract":[]}
main_url = "https://citeseerx.ist.psu.edu/search?q=information+retrieval&t=doc&sort=rlv&start={}"
for page_num in range(0, 5000, 10):
    
    l1 = Request(main_url.format(page_num), headers={'User-Agent': 'Mozilla/5.0'})
    url1 = urlopen(l1)

    d1 = url1.read()
    d1_soup = BeautifulSoup(d1)
    
    
    for i in d1_soup.find_all("a", attrs={'class':'remove doc_details'}):
        
        result["Title"].append(i.text.strip())
        
    for i in d1_soup.find_all("div", attrs={'class':'pubinfo'}):
        
        if len(i.find_all("span")) < 2:
            result["Authors"].append(i.find_all("span")[0].text.replace(" ", "").replace("\n", " ").split()[1])
            result['Year'].append(0)

        elif len(i.find_all("span")) > 2:
            result["Authors"].append(i.find_all("span")[0].text.replace(" ", "").replace("\n", " ").split()[1])
            result['Year'].append(i.find_all("span")[2].text.split()[1])
        
        else:
            result["Authors"].append(i.find_all("span")[0].text.replace(" ", "").replace("\n", " ").split()[1])
            result['Year'].append(i.find_all("span")[1].text.split()[1])
    for i in d1_soup.find_all("div", attrs={'class':'snippet'}):
        
        result["Abstract"].append(i.text)
    
    
print(len(result["Title"]))
print(len(result["Authors"]))
print(len(result["Year"]))
print(len(result["Abstract"]))
df = pd.DataFrame(result)
print(df.head())
print(df.shape)

500
500
500
500
                                               Title  \
0                              Information Retrieval
1                       Modern Information Retrieval
2                      Private Information Retrieval
3           An Introduction to Information Retrieval
4  Naive (Bayes) at Forty: The Independence Assum...

                                   Authors  Year  \
0                        C.J.vanRijsbergen  1979
1  RicardoBaeza-Yates,BerthierRibeiro-Neto  1999
2                          BennyChor,etal.     0
3               ChristopherD.Manning,etal.  2007
4                             DavidD.Lewis  1998

                                            Abstract
0                                        "...   ..."
1  "... Information retrieval (IR) has changed co...
2  "...   We describe schemes that enable a user ...
3                                        "...   ..."
4  "... The naive Bayes classifier, currently exp...
(500, 4)

Question 4 (10 points): Write python code to collect 1000 posts from Twitter, or Facebook, or Instagram. You can either use hashtags, keywords, user_name, user_id, or other information to collect the data. 

The following information needs to be collected:

(1) User_name

(2) Posted time

(3) Text

In [ ]:
import tweepy
import pandas as pd
query = 'Coronavirus'
maximumtweets = 1000
cons_key = "2Em7SxlX9jPMfL4x97r3zMO0x"
consr_secret = "sVbJzekKuiAgq83Y7gCwNVbSowqQokGVzWexKHl2cXIPceWtSd"
token = "1439767876962029572-uUMt8oWRyzj9ilE5zk4uYbL93sCMPT"
secret_token = "oydIGymn9bS767FVEMawE9GyGAnMmBJfaY2XXKmHnmliF"
auth = tweepy.OAuthHandler(cons_key, consr_secret)
auth.set_access_token(token, secret_token)
api = tweepy.API(auth,wait_on_rate_limit=True)
tweet = tweepy.Cursor(api.search,q=query,lang='en').items(maximumtweets)
tweet_list = [[twt.text, twt.created_at, twt.id_str, twt.user.name, twt.user.screen_name, twt.user.id_str, twt.user.location, twt.user.url, twt.user.description, twt.user.verified, twt.user.followers_count, twt.user.friends_count, twt.user.favourites_count, twt.user.statuses_count, twt.user.listed_count, twt.user.created_at, twt.user.profile_image_url_https, twt.user.default_profile, twt.user.default_profile_image] for twt in tweet]
tweet_df = pd.DataFrame(tweet_list)

Tweets = pd.DataFrame()
Tweets['User_Name'] = tweet_df[4]
Tweets['Posted_Time'] = tweet_df[1]
Tweets['Text'] = tweet_df[0]
Tweets
tweet_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,RT @itsdjpriminista: is now playing ♫: #JP - #...,2022-09-26 04:06:36,1574249049934405633,Héphaïstos,hephaistos_ai,1151202637582348294,Paris,https://t.co/r220FT6JBq,Héphaïstos has won 5 competitions and is frequ...,False,4607,207,262536,393554,13,2019-07-16 18:51:11,https://pbs.twimg.com/profile_images/140158061...,True,False
1,is now playing ♫: #JP - #Covid-19_Modern_Warfa...,2022-09-26 04:06:31,1574249028304478208,Dj Priminista [LIVE],itsdjpriminista,782937333498781696,🇬🇧🇬🇭🇯🇲🇺🇸 #WORLWIDE,https://t.co/3MMALs8ar3,"Proud Father,VYBZ FAMILY INNA CLASS, DJ https:...",False,126,201,2494,43664,1,2016-10-03 13:36:21,https://pbs.twimg.com/profile_images/154269849...,True,False
2,RT @hbcu_shitposter: Me in 2040: So there was ...,2022-09-26 04:06:23,1574248995131629569,Patrick Holderby,QwertyClergy1,1375465216994115586,"Tennessee, USA",None,I play Pokémon and drink monster,False,12,114,894,114,0,2021-03-26 15:10:45,https://pbs.twimg.com/profile_images/143255065...,True,False
3,RT @profesterman: Cases of new COVID-19 varian...,2022-09-26 04:06:20,1574248982242799616,Chris Munro,ChrisClme,972888836,,None,Compassion and Respect~ Retweets do not necess...,False,506,711,12632,56539,55,2012-11-26 23:18:30,https://pbs.twimg.com/profile_images/147569205...,True,False
4,@Jim_Jordan VIDEO: Trump Got Secretly Vaccinat...,2022-09-26 04:05:32,1574248780647448576,ValeriusX,x_valerius,1564629698528702470,Ulthar,None,Gandhi — “The greatness of humanity is not in ...,False,12,15,239,1876,0,2022-08-30 15:03:15,https://pbs.twimg.com/profile_images/156469405...,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Me in 2040: So there was this gorilla that got...,2022-09-25 23:48:40,1574184139737255936,Blessed Shitposter 🇻🇦,hbcu_shitposter,1489014408248496131,"Vienna, Austria",None,Deus Vult ☧ 🏛🇻🇦 ⚔️ 🛡also anime ramblings,False,310,1665,1732,1034,6,2022-02-02 23:14:42,https://pbs.twimg.com/profile_images/156949737...,True,False
996,RT @AimHardoi: Most Important information beca...,2022-09-25 23:48:33,1574184109832040448,D' brahmin °π°,brahmonamah,1394040438290407425,,None,जटाटवीगलज्जल प्रवाहपावितस्थले\n\nगलेऽवलम्ब्य ल...,False,53,591,121,779,0,2021-05-16 21:22:15,https://pbs.twimg.com/profile_images/140297147...,True,False
997,RT @jamesvgingerich: #WhosNext? Surely the se...,2022-09-25 23:48:15,1574184033688457217,Derossi Sieyodji,DerossiS,347318132,"Douala, Cameroon",https://t.co/pSiIJVjLMy,"Logistics is my philosophy, I respect the cons...",False,241,920,2465,1682,0,2011-08-02 16:22:17,https://pbs.twimg.com/profile_images/156977865...,True,False
998,RT @jsolomonReports: Feds award $1 million to ...,2022-09-25 23:47:56,1574183955351339008,Kelly Cunningham,krccanuck,1055536236,,None,,False,191,69,50512,96136,3,2013-01-02 16:43:14,https://abs.twimg.com/sticky/default_profile_i...,True,True
999,Watching an episode of Law &amp; Order from 20...,2022-09-25 23:47:28,1574183838057742337,Lakeya,MsSpencer_xoxo,269082707,North Carolina,None,,False,625,741,22924,29672,0,2011-03-20 02:20:33,https://pbs.twimg.com/profile_images/155342342...,False,False